version: "3.9"

services:
  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "4000:4000"
    depends_on:
      - userservice
      - cardcollection
      - battleengine
    environment:
      USER_HOST: userservice
      USER_PORT: 6001
      CARD_HOST: cardcollection
      CARD_PORT: 4001
      BATTLE_HOST: battleengine
      BATTLE_PORT: 6003

  userservice:
    build: ./userservice
    container_name: userservice
    expose:
      - "6001"
    environment:
      HOST: 0.0.0.0
      PORT: 6001

  cardcollection:
    build: ./cardcollection/CardCollection
    container_name: cardcollection
    expose:
      - "4001"
    environment:
      HOST: 0.0.0.0
      PORT: 4001

  battleengine:
    build: ./battleengine
    container_name: battleengine
    expose:
      - "6003"
    environment:
      HOST: 0.0.0.0
      PORT: 6003

  client:
    build: ./client
    container_name: client
    depends_on:
      - gateway
    environment:
      GATEWAY_HOST: gateway
      GATEWAY_PORT: 4000
